name: Deploy to Azure VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Build frontend before sending
      - name: Build frontend
        working-directory: frontend
        run: |
          npm install
          npm run build

      # Package backend + built frontend
      - name: Package project
        run: tar -czf retailtech.tar.gz backend frontend/build

      - name: Copy files to Azure VM
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.AZURE_VM_IP }}
          username: ${{ secrets.AZURE_VM_USER }}
          key: ${{ secrets.AZURE_VM_SSH_KEY }}
          source: "retailtech.tar.gz"
          target: "/home/${{ secrets.AZURE_VM_USER }}/"

      - name: Deploy on Azure VM
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.AZURE_VM_IP }}
          username: ${{ secrets.AZURE_VM_USER }}
          key: ${{ secrets.AZURE_VM_SSH_KEY }}
          script: |
            cd /home/${{ secrets.AZURE_VM_USER }}
            rm -rf retailtech
            mkdir retailtech
            tar -xzf retailtech.tar.gz -C retailtech
            cd retailtech/backend
            npm install
            pm2 stop retailtech || true
            pm2 start app.js --name retailtech --watch
            sudo rm -rf /var/www/html/*
            sudo cp -r ../frontend/build/* /var/www/html/
            echo "Deployment successful" >> deploy.log
